korpa/urls.py
from django.urls import path
from . import views

app_name = 'korpa'

urlpatterns = [
    path('', views.korpa_detaljno, name='korpa_detaljno'),
    path('dodaj/<int:proizvod_id>/', views.korpa_dodaj, name='korpa_dodaj'),
    path('ukloni/<int:proizvod_id>/',
         views.korpa_ukloni,
         name='korpa_ukloni'),
]

kuponi/urls.py
from django.urls import path
from . import views
from django.utils.text import gettext_lazy as _

app_name = 'kuponi'

urlpatterns = [
    path(_('dodaj/'), views.kupon_dodaj, name='dodaj'),
]

narudzbina/urls.py
from django.urls import path
from . import views
from django.utils.text import gettext_lazy as _

app_name = 'narudzbina'

urlpatterns = [
    path(_('kreiraj/'), views.narudzbina_dodaj, name='narudzbina_dodaj'),
    path('admin/narudzbina/<int:narudzbina_id>/', views.admin_narudzbina_detaljno,
         name='admin_narudzbina_detaljno'),
    path('admin/narudzbina/pdf/<int:narudzbina_id>/', views.admin_narudzbina_pdf,
         name='admin_narudzbina_pdf')
]

prodavnica/urls.py
from django.urls import path
from . import views

app_name = 'prodavnica'

urlpatterns = [
    path('', views.proizvodi_lista, name='proizvodi_lista'),
    path('<slug:kategorija_slug>/',
         views.proizvodi_lista,
         name='proizvodi_lista_kategorija'),
    path('<int:id>/<slug:proizvod_slug>/',
         views.proizvod_detaljno,
         name='proizvod_detaljno'),
]

projekat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.text import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('korpa/'), include('korpa.urls', namespace='korpa')),
    path(_('narudzbina/'), include('narudzbina.urls', namespace='narudzbina')),
    path(_('placanje/'), include('placanje.urls', namespace='placanje')),
    path(_('kuponi/'), include('kuponi.urls', namespace='kuponi')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('prodavnica.urls', namespace='prodavnica')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

korpa/models.py
from django.db import models

korpa/forms.py
from django import forms
from django.utils.text import gettext_lazy as _
PROIZVOD_KOLICINA_CHOICES = [(i, str(i))for i in range(1, 21)]


class KorpaDodajProizvodForma(forms.Form):
    kolicina = forms.TypedChoiceField(
        coerce=int, choices=PROIZVOD_KOLICINA_CHOICES, label=_('Kolicina'))
    azuriraj = forms.BooleanField(
        required=False, widget=forms.HiddenInput, initial=False)

korpa/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from prodavnica.models import Proizvod
from .forms import KorpaDodajProizvodForma
from .korpa import Korpa
from kuponi.forms import KuponDodajForma
from prodavnica.preporuceno import Preporucivac


@require_POST
def korpa_dodaj(request, proizvod_id):
    korpa = Korpa(request)
    proizvod = get_object_or_404(Proizvod, id=proizvod_id)
    forma = KorpaDodajProizvodForma(request.POST)
    if forma.is_valid():
        cd = forma.cleaned_data
        korpa.dodaj(proizvod=proizvod,
                    kolicina=cd['kolicina'],
                    azuriraj_kolicinu=cd['azuriraj'])
    return redirect('korpa:korpa_detaljno')


def korpa_ukloni(request, proizvod_id):
    korpa = Korpa(request)
    proizvod = get_object_or_404(Proizvod, id=proizvod_id)
    korpa.ukloni(proizvod)
    return redirect('korpa:korpa_detaljno')


def korpa_detaljno(request):
    korpa = Korpa(request)
    for predmet in korpa:
        predmet['azuriraj_kolicinu_forma'] = KorpaDodajProizvodForma(
            initial={'kolicina': predmet['kolicina'],
                     'azuriraj': True}
        )
    kupon_dodaj_forma = KuponDodajForma()
    p = Preporucivac()
    korpa_proizvodi = [predmet['proizvod'] for predmet in korpa]
    preporuceni_proizvodi = p.preporuci_proizvode_za(korpa_proizvodi)
    return render(request, 'korpa/detaljno.html', {
        'korpa': korpa,
        'kupon_dodaj_forma': kupon_dodaj_forma,
        'preporuceni_proizvodi': preporuceni_proizvodi})

templates/korpa/detaljno.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Vasa korpa' %}
{% endblock title %}

{% block content %}
    <h1>{% trans 'Vasa korpa' %}</h2>
    <table class="cart">
        <thead>
            <tr>
                <th>{% trans 'Slika' %}</th>
                <th>{% trans 'Proizvod' %}</th>
                <th>{% trans 'Kolicina' %}</th>
                <th>{% trans 'Ukloni' %}</th>
                <th>{% trans 'Cena po jedinici' %}</th>
                <th>{% trans 'Cena' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for predmet in korpa %}
            {% with proizvod=predmet.proizvod %}
            <tr>
                <td>
                    <a href="{{proizvod.get_absolute_url}}">
                        <img src="{{proizvod.slika.url}}" alt="" srcset="">
                    </a>
                </td>
                <td><a href="{{proizvod.get_absolute_url}}">{{proizvod.ime}}</td></a>
                <td>
                    <form action="{% url 'korpa:korpa_dodaj' proizvod.id %}" method="post">
                        {{predmet.azuriraj_kolicinu_forma.kolicina}}
                        {{predmet.azuriraj_kolicinu_forma.azuriraj}}
                        <input type="submit" value="{% trans 'Azuriraj' %}">
                        {% csrf_token %}
                    </form>
                </td>
                <td>
                    <a href="{% url 'korpa:korpa_ukloni' proizvod.id %}">{% trans 'Ukloni' %}</a>
                </td>
                <td class="num">{{predmet.cena}}</td>
                <td class="num">{{predmet.puna_cena}}</td>
            </tr>
            {% endwith %}
        {% endfor %}

        {% if korpa.kupon %}
            <tr class="subtotal">
                <td>{% trans 'Kupon' %}:</td>
                <td colspan="4"></td>
                <td class="num">{{korpa.kupon.kod}}</td>
            </tr>
            <tr >
                <td>{% trans 'Popust' %} ({{korpa.kupon.popust}}%):</td>
                <td colspan="4"></td>
                <td class="num neg">- {{korpa.dobij_popust|floatformat:'2'}} RSD </td>
            </tr>
        {% endif %}

            <tr class="total">
                <td>{% trans 'Ukupno' %}:</td>
                <td colspan="4"></td>
                <td class="num">RSD {{korpa.dobij_punu_cenu_posle_popusta|floatformat:'2'}}</td>
            </tr>
        </tbody>
    </table>
    <p>{% trans 'Unesite kod kupona' %}:</p>
    <form action="{% url 'kuponi:dodaj' %}" method="post">
        {{kupon_dodaj_forma}}
        {% csrf_token %}
        <input type="submit" value="{% trans 'Potvrdi' %}">
    </form>
    <p class="text-right">
        <a href="{% url 'prodavnica:proizvodi_lista' %}" class="button light">{% trans 'Nastavite sa kupovinom' %}</a>
        <a href="{% url 'narudzbina:narudzbina_dodaj' %}" class="button">{% trans 'Idi na kasu' %}</a>
    </p>
    {% if preporuceni_proizvodi %}
        <div class="recommendations cart">
            <h3>{% trans 'Preporuceni proizvodi za vas' %}:</h3>
            {% for proizvod in preporuceni_proizvodi %}
            <div class="item">
                <a href="{{proizvod.get_absolute_url}}">
                    <img src="{{proizvod.slika.url}}" alt="">
                </a>
                <p><a href="{{proizvod.get_absolute_url}}">{{proizvod.ime}}</a></p>
            </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock content %}